### ISSUE TITLE
How about the performance compare to nano_gicp using in DLO/DLIO ?

### ISSUE THREAD

**Issue by qpc001** [koide3/small_gicp#13]
reference link: [[nano_gicp]](https://github.com/engcang/nano_gicp)

**Comment by koide3** [comment]
- The core registration algorithm of small_gicp is re-written from scratch to improve the processing speed, and I suppose small_gicp might be faster than nano_gicp, which is based on the previous implementation fast_gicp.
- DLO/DLIO are scan-to-model matching odometry estimation algorithms while small_gicp is a more primitive scan matching algorithm. So, in terms of the accuracy, it is apples-to-oranges comparison. But, I suppose there is no accuracy differences in the context of scan-to-scan matching.
