### ISSUE TITLE
Missing normal vector after downsampling

### ISSUE THREAD

**Issue by mcmingchang** [koide3/small_gicp#29]
I slightly modified the creation method of the point cloud, which can convert the point cloud and normal vector of Open3D normally. However, after voxelization, I output the point with a normal vector value of (0,0,0,0)

![image](https://github.com/koide3/small_gicp/assets/37234299/8fdb3dc0-ea07-4a40-91ac-c83a710e0f37)

**Comment by koide3** [comment]
The downsampling ruins point attributes other than point coordinates. I recommend doing downsampling before normal estimation.
