### ISSUE TITLE
Where can I find definitions/documentation for `RegistrationResult`?

### ISSUE THREAD

**Issue by gabrielnan** [koide3/small_gicp#35]
I'm trying to understand how `RegistrationResult::{H,b,error}` are defined. Please let me know where I can find documentation for these.

**Comment by koide3** [comment]
`error` is the final registration error (the sum of per-point D2D distances in case of GICP), and `H` and `b` are its quadratic approximation parameters. They correspond to the symbols in Eq. 15 of the following paper.

http://www2.informatik.uni-freiburg.de/~stachnis/pdf/grisetti10titsmag.pdf
