### ISSUE TITLE
Conflict of nanoflann namespace issue

### ISSUE THREAD

**Issue by LimHyungTae** [koide3/small_gicp#38]
Hello Koide, thanks for sharing this nice stuff.

I tried to include this repository, and I found that once the repository already contains `nanoflann.hpp`, then two `nanoflann.hpp` brings namespace conflict error.

Of course, it's very easy to resolve by manually changing the workspace name in the own package, but maybe we have to change the namespace of nanoflann.hpp in this repository for better usability (e.g., namespace koide_nanoflann or something)

Thanks!

**Comment by koide3** [comment]
Thanks for reporting the issue. I recently re-implemented KdTree, and I'm considering to replace nanoflann with the new KdTree. It would resolve the conflict and bring (very slight) speed improvement.

**Comment by koide3** [comment]
I replaced nanoflann with a new KdTree implementation in this PR https://github.com/koide3/small_gicp/pull/42 that would resolve the conflict. I'll merge it once some errors on windows are fixed.
