### ISSUE TITLE
Apply for 2D scan matching

### ISSUE THREAD

**Issue by deliangye** [koide3/small_gicp#55]
Hey Koide3, thanks for sharing your great work!
Are there any parameter to need to be tweaked for 2D point clouds ?  I haven't time to check out and test codes yet, but would like to think about it first.

**Comment by Atticuszz** [comment]
hello，did u mean rgd-d image？i am testing its accuracy  in with meta dataset replica，testing room0 now with ，then compare it with pcl and open3d，for gicp now it works definely accurate😄

**Comment by deliangye** [comment]
No, I mean 2D point cloud only including XY, not rgb-d image.

**Comment by koide3** [comment]
In that case, you can try RestrictDoFFactor that restricts optimization axes. https://github.com/koide3/small_gicp/blob/94d93b9e01ddbab805f00f67ed7ca818b3bff202/include/small_gicp/factors/general_factor.hpp#L43
