### ISSUE TITLE
segmentation fault on Mac OS 14.5 with Apple M2

### ISSUE THREAD

**Issue by liueryun** [koide3/small_gicp#64]
**Describe the bug**
I install the python package via pip, and got segmentation fault crash while import small_gicp.

>>> import small_gicp
zsh: segmentation fault  python

**Comment by koide3** [comment]
Thank you for reporting the issue. Can you see if the segfault happens with source build (`pip install .`)?

Because I don't have a local mac, and I would appreciate if you could help me find the cause of the issue.

**Comment by liueryun** [comment]
It's OK with source build! Thank you.
