### ISSUE TITLE
Old PCL version detected. Please update PCL to 1.11 or later

### ISSUE THREAD

**Issue by G4419** [koide3/small_gicp#87]
My ROS version is Noetic. Even though I have specified PCL version 1.14 in the CMakeLists, I am still encountering an error with RegistrationPCL stating "Old PCL version detected. Please update PCL to 1.11 or later."

**Comment by G4419** [comment]
Sorry, my bad. I installed PCL in the default directory.

**Comment by AphroraC** [comment]
Hello! I have encountered the same problem too, and I wonder how you solved it later.
@G4419
