### ISSUE TITLE
small_gicp::RegistrationPCL<pcl::PointXYZ, pcl::PointXYZ> reg.getFitnessScore(); error...

### ISSUE THREAD

**Issue by InguChoi** [koide3/small_gicp#88]
**Describe the bug**
I used the function `getFitnessScore();` in the `small_gicp::RegistrationPCL<pcl::PointXYZ, pcl::PointXYZ> reg;`.
It can be builded successfully, but It can not be operated..

The error results is below in the terminal.

> /usr/local/include/pcl-1.14/pcl/kdtree/impl/kdtree_flann.hpp:239: int pcl::KdTreeFLANN<PointT, Dist>::nearestKSearch(const PointT&, unsigned int, pcl::Indices&, std::vector<float>&) const [with PointT = pcl::PointXYZ; Dist = flann::L2_Simple<float>; pcl::Indices = std::vector<int>]: Assertion `point_representation_->isValid (point) && "Invalid (NaN, Inf) point coordinates given to nearestKSearch!"' failed.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04
 - Language C++

**Comment by Xiangzhaohong** [comment]
removeNAN for the input clouds first?

**Comment by InguChoi** [comment]
> removeNAN for the input clouds first?

Your comment is right.

The point cloud data from my bag file is needed to pre-processing such as NAN, INFINITE.

```
inline void removeNaNAndInfinitePoints(pcl::PointCloud<pcl::PointXYZ>::Ptr& cloud)
{
    pcl::PointCloud<pcl::PointXYZ>::Ptr filtered_cloud(new pcl::PointCloud<pcl::PointXYZ>());
    int valid_points = 0;

    for (const auto& point : cloud->points) {
        if (std::isfinite(point.x) && std::isfinite(point.y) && std::isfinite(point.z)) {
            filtered_cloud->points.push_back(point); 
            valid_points++;
        }
    }
    cloud.swap(filtered_cloud);
}
```

**Comment by koide3** [comment]
FYI: `pcl::removeNaNFromPointCloud` would be useful for this purpose.
https://pointclouds.org/documentation/group__filters.html#ga9de762e05951938f074479c3bf8ae084
