### ISSUE TITLE
question about the tbb usage in downsample module

### ISSUE THREAD

**Issue by geniusdo** [koide3/small_gicp#93]
Thank you for your great job, I've been following your job for time.  
A small question here.  
Here std::vector write operation is performed in tbb::parallel_for. Wouldn't it be thread-unsafe with my knowledge.  
I tested similar code on my computer, there seemed to be no any problem yet. However, is it safe to still use this function in power-limited environment?
![image](https://github.com/user-attachments/assets/42313b7c-2767-4db4-bd2b-77dc5d15cf7d)

**Comment by geniusdo** [comment]
I see tbb also offers a thread-safe container. Would you recommend to use that in this situation?

**Comment by koide3** [comment]
This kind of "map" operations can safely be done on `std::vector` as each process in the for loop is independent of each other. See the following pages to get more details.

https://oneapi-src.github.io/oneTBB/main/tbb_userguide/design_patterns/Design_Patterns.html
https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Containers.html

**Comment by geniusdo** [comment]
Thanks for your reply. I checked that it's thread safe to modify a vector in different location in memory. Closing this issue.

**Comment by geniusdo** [comment]
Thanks for your reply. I checked that it's thread safe to modify a vector in different location in memory. Closing this issue.
